name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        clean: true  # Додаємо цю опцію для очищення

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        mkdir -p test-reports
        python manage.py test --verbosity=2 --no-input --parallel --keepdb --junit-xml=test-reports/test-results.xml

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-reports/test-results.xml

    - name: Create Artifact
      run: |
        zip -r my_project_artifact.zip .  # Створюємо zip-архів з усіма файлами проекту

    - name: Upload Project Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my_project_artifact
        path: my_project_artifact.zip
